### ISSUE TITLE
AJAX handler 'onDelete' was not found

### ISSUE THREAD

**Issue by warner-steve** [MaviTm/compon#1]
[Compon_october_ajax.pdf](https://github.com/MaviTm/compon/files/491195/Compon_october_ajax.pdf)
Trying to delete a carousel subitem go the message that AJAX handler 'onDelete' was not found.

**Comment by mavitm** [comment]
Hello stevwarner
I'm sorry for the trouble. 
I applied some updates and I edited the problem.
Please update to the new version.
Thank you so much
